# Generated by Django 2.2 on 2021-04-10 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_text', models.CharField(max_length=400, null=True)),
                ('filled', models.BooleanField(default=False)),
                ('answer', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='subQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_question_display_text', models.CharField(max_length=400, null=True)),
                ('main_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Question')),
            ],
        ),
    ]
